// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAilGwj3l-Od-_hKySKlzcgPk9xFtNsTYQ',
    appId: '1:85174181615:web:5172b815db0366b16ec51a',
    messagingSenderId: '85174181615',
    projectId: 'louzero',
    authDomain: 'louzero.firebaseapp.com',
    storageBucket: 'louzero.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA70YWrFVdIyxfVNnGdIRo6IY4q9qVvBY',
    appId: '1:85174181615:android:aab1178c92b69d2f6ec51a',
    messagingSenderId: '85174181615',
    projectId: 'louzero',
    storageBucket: 'louzero.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgyagQ7oa-7uEXId8EA-AfdbE_Zz05EM',
    appId: '1:85174181615:ios:e3820a0927c53c686ec51a',
    messagingSenderId: '85174181615',
    projectId: 'louzero',
    storageBucket: 'louzero.appspot.com',
    androidClientId: '85174181615-cn1hdi7blm63jkj665jghp2a878jlftg.apps.googleusercontent.com',
    iosClientId: '85174181615-ag8sc0dl8b2vu0s499b4v09hoqe83n0q.apps.googleusercontent.com',
    iosBundleId: 'com.evosus.louzero',
  );
}
