class CountryCode {
  final String code;
  final String name;
  CountryCode({required this.name, required this.code});
}

// iso3166 1 alpha 2
abstract class CountryCodes {
  static List<CountryCode> shortList = [
    CountryCode(code: "CA", name: "Canada"),
    CountryCode(code: "MX", name: "Mexico"),
    CountryCode(code: "US", name: "United States")
  ];

  static List<CountryCode> list = [
    CountryCode(code: "CA", name: "Canada"),
    CountryCode(code: "MX", name: "Mexico"),
    CountryCode(code: "US", name: "United States"),
    CountryCode(code: "AF", name: "Afghanistan"),
    CountryCode(code: "AX", name: "Aland Islands"),
    CountryCode(code: "AL", name: "Albania"),
    CountryCode(code: "DZ", name: "Algeria"),
    CountryCode(code: "AS", name: "American Samoa"),
    CountryCode(code: "AD", name: "Andorra"),
    CountryCode(code: "AO", name: "Angola"),
    CountryCode(code: "AI", name: "Anguilla"),
    CountryCode(code: "AQ", name: "Antarctica"),
    CountryCode(code: "AG", name: "Antigua And Barbuda"),
    CountryCode(code: "AR", name: "Argentina"),
    CountryCode(code: "AM", name: "Armenia"),
    CountryCode(code: "AW", name: "Aruba"),
    CountryCode(code: "AU", name: "Australia"),
    CountryCode(code: "AT", name: "Austria"),
    CountryCode(code: "AZ", name: "Azerbaijan"),
    CountryCode(code: "BS", name: "Bahamas"),
    CountryCode(code: "BH", name: "Bahrain"),
    CountryCode(code: "BD", name: "Bangladesh"),
    CountryCode(code: "BB", name: "Barbados"),
    CountryCode(code: "BY", name: "Belarus"),
    CountryCode(code: "BE", name: "Belgium"),
    CountryCode(code: "BZ", name: "Belize"),
    CountryCode(code: "BJ", name: "Benin"),
    CountryCode(code: "BM", name: "Bermuda"),
    CountryCode(code: "BT", name: "Bhutan"),
    CountryCode(code: "BO", name: "Bolivia"),
    CountryCode(code: "BA", name: "Bosnia And Herzegovina"),
    CountryCode(code: "BW", name: "Botswana"),
    CountryCode(code: "BV", name: "Bouvet Island"),
    CountryCode(code: "BR", name: "Brazil"),
    CountryCode(code: "IO", name: "British Indian Ocean Territory"),
    CountryCode(code: "BN", name: "Brunei Darussalam"),
    CountryCode(code: "BG", name: "Bulgaria"),
    CountryCode(code: "BF", name: "Burkina Faso"),
    CountryCode(code: "BI", name: "Burundi"),
    CountryCode(code: "KH", name: "Cambodia"),
    CountryCode(code: "CM", name: "Cameroon"),
    CountryCode(code: "CV", name: "Cape Verde"),
    CountryCode(code: "KY", name: "Cayman Islands"),
    CountryCode(code: "CF", name: "Central African Republic"),
    CountryCode(code: "TD", name: "Chad"),
    CountryCode(code: "CL", name: "Chile"),
    CountryCode(code: "CN", name: "China"),
    CountryCode(code: "CX", name: "Christmas Island"),
    CountryCode(code: "CC", name: "Cocos (Keeling) Islands"),
    CountryCode(code: "CO", name: "Colombia"),
    CountryCode(code: "KM", name: "Comoros"),
    CountryCode(code: "CG", name: "Congo"),
    CountryCode(code: "CD", name: "Congo, Democratic Republic"),
    CountryCode(code: "CK", name: "Cook Islands"),
    CountryCode(code: "CR", name: "Costa Rica"),
    CountryCode(code: "CI", name: "Cote D\"Ivoire"),
    CountryCode(code: "HR", name: "Croatia"),
    CountryCode(code: "CU", name: "Cuba"),
    CountryCode(code: "CY", name: "Cyprus"),
    CountryCode(code: "CZ", name: "Czech Republic"),
    CountryCode(code: "DK", name: "Denmark"),
    CountryCode(code: "DJ", name: "Djibouti"),
    CountryCode(code: "DM", name: "Dominica"),
    CountryCode(code: "DO", name: "Dominican Republic"),
    CountryCode(code: "EC", name: "Ecuador"),
    CountryCode(code: "EG", name: "Egypt"),
    CountryCode(code: "SV", name: "El Salvador"),
    CountryCode(code: "GQ", name: "Equatorial Guinea"),
    CountryCode(code: "ER", name: "Eritrea"),
    CountryCode(code: "EE", name: "Estonia"),
    CountryCode(code: "ET", name: "Ethiopia"),
    CountryCode(code: "FK", name: "Falkland Islands (Malvinas)"),
    CountryCode(code: "FO", name: "Faroe Islands"),
    CountryCode(code: "FJ", name: "Fiji"),
    CountryCode(code: "FI", name: "Finland"),
    CountryCode(code: "FR", name: "France"),
    CountryCode(code: "GF", name: "French Guiana"),
    CountryCode(code: "PF", name: "French Polynesia"),
    CountryCode(code: "TF", name: "French Southern Territories"),
    CountryCode(code: "GA", name: "Gabon"),
    CountryCode(code: "GM", name: "Gambia"),
    CountryCode(code: "GE", name: "Georgia"),
    CountryCode(code: "DE", name: "Germany"),
    CountryCode(code: "GH", name: "Ghana"),
    CountryCode(code: "GI", name: "Gibraltar"),
    CountryCode(code: "GR", name: "Greece"),
    CountryCode(code: "GL", name: "Greenland"),
    CountryCode(code: "GD", name: "Grenada"),
    CountryCode(code: "GP", name: "Guadeloupe"),
    CountryCode(code: "GU", name: "Guam"),
    CountryCode(code: "GT", name: "Guatemala"),
    CountryCode(code: "GG", name: "Guernsey"),
    CountryCode(code: "GN", name: "Guinea"),
    CountryCode(code: "GW", name: "Guinea-Bissau"),
    CountryCode(code: "GY", name: "Guyana"),
    CountryCode(code: "HT", name: "Haiti"),
    CountryCode(code: "HM", name: "Heard Island & Mcdonald Islands"),
    CountryCode(code: "VA", name: "Holy See (Vatican City State)"),
    CountryCode(code: "HN", name: "Honduras"),
    CountryCode(code: "HK", name: "Hong Kong"),
    CountryCode(code: "HU", name: "Hungary"),
    CountryCode(code: "IS", name: "Iceland"),
    CountryCode(code: "IN", name: "India"),
    CountryCode(code: "ID", name: "Indonesia"),
    CountryCode(code: "IR", name: "Iran, Islamic Republic Of"),
    CountryCode(code: "IQ", name: "Iraq"),
    CountryCode(code: "IE", name: "Ireland"),
    CountryCode(code: "IM", name: "Isle Of Man"),
    CountryCode(code: "IL", name: "Israel"),
    CountryCode(code: "IT", name: "Italy"),
    CountryCode(code: "JM", name: "Jamaica"),
    CountryCode(code: "JP", name: "Japan"),
    CountryCode(code: "JE", name: "Jersey"),
    CountryCode(code: "JO", name: "Jordan"),
    CountryCode(code: "KZ", name: "Kazakhstan"),
    CountryCode(code: "KE", name: "Kenya"),
    CountryCode(code: "KI", name: "Kiribati"),
    CountryCode(code: "KR", name: "Korea"),
    CountryCode(code: "KP", name: "North Korea"),
    CountryCode(code: "KW", name: "Kuwait"),
    CountryCode(code: "KG", name: "Kyrgyzstan"),
    CountryCode(code: "LA", name: "Lao People\"s Democratic Republic"),
    CountryCode(code: "LV", name: "Latvia"),
    CountryCode(code: "LB", name: "Lebanon"),
    CountryCode(code: "LS", name: "Lesotho"),
    CountryCode(code: "LR", name: "Liberia"),
    CountryCode(code: "LY", name: "Libyan Arab Jamahiriya"),
    CountryCode(code: "LI", name: "Liechtenstein"),
    CountryCode(code: "LT", name: "Lithuania"),
    CountryCode(code: "LU", name: "Luxembourg"),
    CountryCode(code: "MO", name: "Macao"),
    CountryCode(code: "MK", name: "Macedonia"),
    CountryCode(code: "MG", name: "Madagascar"),
    CountryCode(code: "MW", name: "Malawi"),
    CountryCode(code: "MY", name: "Malaysia"),
    CountryCode(code: "MV", name: "Maldives"),
    CountryCode(code: "ML", name: "Mali"),
    CountryCode(code: "MT", name: "Malta"),
    CountryCode(code: "MH", name: "Marshall Islands"),
    CountryCode(code: "MQ", name: "Martinique"),
    CountryCode(code: "MR", name: "Mauritania"),
    CountryCode(code: "MU", name: "Mauritius"),
    CountryCode(code: "YT", name: "Mayotte"),
    CountryCode(code: "FM", name: "Micronesia, Federated States Of"),
    CountryCode(code: "MD", name: "Moldova"),
    CountryCode(code: "MC", name: "Monaco"),
    CountryCode(code: "MN", name: "Mongolia"),
    CountryCode(code: "ME", name: "Montenegro"),
    CountryCode(code: "MS", name: "Montserrat"),
    CountryCode(code: "MA", name: "Morocco"),
    CountryCode(code: "MZ", name: "Mozambique"),
    CountryCode(code: "MM", name: "Myanmar"),
    CountryCode(code: "NA", name: "Namibia"),
    CountryCode(code: "NR", name: "Nauru"),
    CountryCode(code: "NP", name: "Nepal"),
    CountryCode(code: "NL", name: "Netherlands"),
    CountryCode(code: "AN", name: "Netherlands Antilles"),
    CountryCode(code: "NC", name: "New Caledonia"),
    CountryCode(code: "NZ", name: "New Zealand"),
    CountryCode(code: "NI", name: "Nicaragua"),
    CountryCode(code: "NE", name: "Niger"),
    CountryCode(code: "NG", name: "Nigeria"),
    CountryCode(code: "NU", name: "Niue"),
    CountryCode(code: "NF", name: "Norfolk Island"),
    CountryCode(code: "MP", name: "Northern Mariana Islands"),
    CountryCode(code: "NO", name: "Norway"),
    CountryCode(code: "OM", name: "Oman"),
    CountryCode(code: "PK", name: "Pakistan"),
    CountryCode(code: "PW", name: "Palau"),
    CountryCode(code: "PS", name: "Palestinian Territory, Occupied"),
    CountryCode(code: "PA", name: "Panama"),
    CountryCode(code: "PG", name: "Papua New Guinea"),
    CountryCode(code: "PY", name: "Paraguay"),
    CountryCode(code: "PE", name: "Peru"),
    CountryCode(code: "PH", name: "Philippines"),
    CountryCode(code: "PN", name: "Pitcairn"),
    CountryCode(code: "PL", name: "Poland"),
    CountryCode(code: "PT", name: "Portugal"),
    CountryCode(code: "PR", name: "Puerto Rico"),
    CountryCode(code: "QA", name: "Qatar"),
    CountryCode(code: "RE", name: "Reunion"),
    CountryCode(code: "RO", name: "Romania"),
    CountryCode(code: "RU", name: "Russian Federation"),
    CountryCode(code: "RW", name: "Rwanda"),
    CountryCode(code: "BL", name: "Saint Barthelemy"),
    CountryCode(code: "SH", name: "Saint Helena"),
    CountryCode(code: "KN", name: "Saint Kitts And Nevis"),
    CountryCode(code: "LC", name: "Saint Lucia"),
    CountryCode(code: "MF", name: "Saint Martin"),
    CountryCode(code: "PM", name: "Saint Pierre And Miquelon"),
    CountryCode(code: "VC", name: "Saint Vincent And Grenadines"),
    CountryCode(code: "WS", name: "Samoa"),
    CountryCode(code: "SM", name: "San Marino"),
    CountryCode(code: "ST", name: "Sao Tome And Principe"),
    CountryCode(code: "SA", name: "Saudi Arabia"),
    CountryCode(code: "SN", name: "Senegal"),
    CountryCode(code: "RS", name: "Serbia"),
    CountryCode(code: "SC", name: "Seychelles"),
    CountryCode(code: "SL", name: "Sierra Leone"),
    CountryCode(code: "SG", name: "Singapore"),
    CountryCode(code: "SK", name: "Slovakia"),
    CountryCode(code: "SI", name: "Slovenia"),
    CountryCode(code: "SB", name: "Solomon Islands"),
    CountryCode(code: "SO", name: "Somalia"),
    CountryCode(code: "ZA", name: "South Africa"),
    CountryCode(code: "GS", name: "South Georgia And Sandwich Isl."),
    CountryCode(code: "ES", name: "Spain"),
    CountryCode(code: "LK", name: "Sri Lanka"),
    CountryCode(code: "SD", name: "Sudan"),
    CountryCode(code: "SR", name: "Suriname"),
    CountryCode(code: "SJ", name: "Svalbard And Jan Mayen"),
    CountryCode(code: "SZ", name: "Swaziland"),
    CountryCode(code: "SE", name: "Sweden"),
    CountryCode(code: "CH", name: "Switzerland"),
    CountryCode(code: "SY", name: "Syrian Arab Republic"),
    CountryCode(code: "TW", name: "Taiwan"),
    CountryCode(code: "TJ", name: "Tajikistan"),
    CountryCode(code: "TZ", name: "Tanzania"),
    CountryCode(code: "TH", name: "Thailand"),
    CountryCode(code: "TL", name: "Timor-Leste"),
    CountryCode(code: "TG", name: "Togo"),
    CountryCode(code: "TK", name: "Tokelau"),
    CountryCode(code: "TO", name: "Tonga"),
    CountryCode(code: "TT", name: "Trinidad And Tobago"),
    CountryCode(code: "TN", name: "Tunisia"),
    CountryCode(code: "TR", name: "Turkey"),
    CountryCode(code: "TM", name: "Turkmenistan"),
    CountryCode(code: "TC", name: "Turks And Caicos Islands"),
    CountryCode(code: "TV", name: "Tuvalu"),
    CountryCode(code: "UG", name: "Uganda"),
    CountryCode(code: "UA", name: "Ukraine"),
    CountryCode(code: "AE", name: "United Arab Emirates"),
    CountryCode(code: "GB", name: "United Kingdom"),
    CountryCode(code: "UM", name: "United States Outlying Islands"),
    CountryCode(code: "UY", name: "Uruguay"),
    CountryCode(code: "UZ", name: "Uzbekistan"),
    CountryCode(code: "VU", name: "Vanuatu"),
    CountryCode(code: "VE", name: "Venezuela"),
    CountryCode(code: "VN", name: "Vietnam"),
    CountryCode(code: "VG", name: "Virgin Islands, British"),
    CountryCode(code: "VI", name: "Virgin Islands, U.S."),
    CountryCode(code: "WF", name: "Wallis And Futuna"),
    CountryCode(code: "EH", name: "Western Sahara"),
    CountryCode(code: "YE", name: "Yemen"),
    CountryCode(code: "ZM", name: "Zambia"),
    CountryCode(code: "ZW", name: "Zimbabwe")
  ];

  static CountryCode? countryCodeByName(String countryName) {
    try {
      return list.firstWhere((country) => country.name == countryName);
    } catch(e) {
      return null;
    }
  }
}
