class CountryCode {
  final String name;
  final String code;
  CountryCode({required this.name, required this.code});
}

abstract class CountryCodes {
  static List<CountryCode> list = [
    CountryCode(name: 'United States', code: 'US'),
    CountryCode(name: 'Canada', code: 'CA'),
    // CountryCode(name: 'Mexico', code: 'MX'),
    // CountryCode(name: 'Afghanistan', code: 'AF'),
    // CountryCode(name: 'Albania', code: 'AL'),
    // CountryCode(name: 'Algeria', code: 'DZ'),
    // CountryCode(name: 'American Samoa', code: 'AS'),
    // CountryCode(name: 'AndorrA', code: 'AD'),
    // CountryCode(name: 'Angola', code: 'AO'),
    // CountryCode(name: 'Anguilla', code: 'AI'),
    // CountryCode(name: 'Antarctica', code: 'AQ'),
    // CountryCode(name: 'Antigua and Barbuda', code: 'AG'),
    // CountryCode(name: 'Armenia', code: 'AM'),
    // CountryCode(name: 'Aruba', code: 'AW'),
    // CountryCode(name: 'Australia', code: 'AU'),
    // CountryCode(name: 'Austria', code: 'AT'),
    // CountryCode(name: 'Azerbaijan', code: 'AZ'),
    // CountryCode(name: 'Bahamas', code: 'BS'),
    // CountryCode(name: 'Bahrain', code: 'BH'),
    // CountryCode(name: 'Bangladesh', code: 'BD'),
    // CountryCode(name: 'Barbados', code: 'BB'),
    // CountryCode(name: 'Belarus', code: 'BY'),
    // CountryCode(name: 'Belgium', code: 'BE'),
    // CountryCode(name: 'Belize', code: 'BZ'),
    // CountryCode(name: 'Benin', code: 'BJ'),
    // CountryCode(name: 'Bermuda', code: 'BM'),
    // CountryCode(name: 'Bhutan', code: 'BT'),
    // CountryCode(name: 'Bolivia', code: 'BO'),
    // CountryCode(name: 'Bosnia and Herzegovina', code: 'BA'),
    // CountryCode(name: 'Botswana', code: 'BW'),
    // CountryCode(name: 'Bouvet Island', code: 'BV'),
    // CountryCode(name: 'Brazil', code: 'BR'),
    // CountryCode(name: 'Bulgaria', code: 'BG'),
    // CountryCode(name: 'Burkina Faso', code: 'BF'),
    // CountryCode(name: 'Burundi', code: 'BI'),
    // CountryCode(name: 'Cambodia', code: 'KH'),
    // CountryCode(name: 'Cameroon', code: 'CM'),
    // CountryCode(name: 'Cape Verde', code: 'CV'),
    // CountryCode(name: 'Cayman Islands', code: 'KY'),
    // CountryCode(name: 'Chad', code: 'TD'),
    // CountryCode(name: 'Chile', code: 'CL'),
    // CountryCode(name: 'China', code: 'CN'),
    // CountryCode(name: 'Christmas Island', code: 'CX'),
    // CountryCode(name: 'Colombia', code: 'CO'),
    // CountryCode(name: 'Comoros', code: 'KM'),
    // CountryCode(name: 'Congo', code: 'CG'),
    // CountryCode(name: 'Cook Islands', code: 'CK'),
    // CountryCode(name: 'Costa Rica', code: 'CR'),
    // CountryCode(name: 'Croatia', code: 'HR'),
    // CountryCode(name: 'Cuba', code: 'CU'),
    // CountryCode(name: 'Cyprus', code: 'CY'),
    // CountryCode(name: 'Czech Republic', code: 'CZ'),
    // CountryCode(name: 'Denmark', code: 'DK'),
    // CountryCode(name: 'Djibouti', code: 'DJ'),
    // CountryCode(name: 'Dominica', code: 'DM'),
    // CountryCode(name: 'Dominican Republic', code: 'DO'),
    // CountryCode(name: 'Ecuador', code: 'EC'),
    // CountryCode(name: 'Egypt', code: 'EG'),
    // CountryCode(name: 'El Salvador', code: 'SV'),
    // CountryCode(name: 'Equatorial Guinea', code: 'GQ'),
    // CountryCode(name: 'Eritrea', code: 'ER'),
    // CountryCode(name: 'Estonia', code: 'EE'),
    // CountryCode(name: 'Ethiopia', code: 'ET'),
    // CountryCode(name: 'Faroe Islands', code: 'FO'),
    // CountryCode(name: 'Fiji', code: 'FJ'),
    // CountryCode(name: 'Finland', code: 'FI'),
    // CountryCode(name: 'France', code: 'FR'),
    // CountryCode(name: 'Gabon', code: 'GA'),
    // CountryCode(name: 'Gambia', code: 'GM'),
    // CountryCode(name: 'Georgia', code: 'GE'),
    // CountryCode(name: 'Germany', code: 'DE'),
    // CountryCode(name: 'Ghana', code: 'GH'),
    // CountryCode(name: 'Gibraltar', code: 'GI'),
    // CountryCode(name: 'Greece', code: 'GR'),
    // CountryCode(name: 'Greenland', code: 'GL'),
    // CountryCode(name: 'Grenada', code: 'GD'),
    // CountryCode(name: 'Guadeloupe', code: 'GP'),
    // CountryCode(name: 'Guam', code: 'GU'),
    // CountryCode(name: 'Guatemala', code: 'GT'),
    // CountryCode(name: 'Guernsey', code: 'GG'),
    // CountryCode(name: 'Guinea', code: 'GN'),
    // CountryCode(name: 'Guyana', code: 'GY'),
    // CountryCode(name: 'Haiti', code: 'HT'),
    // CountryCode(name: 'Honduras', code: 'HN'),
    // CountryCode(name: 'Hong Kong', code: 'HK'),
    // CountryCode(name: 'Hungary', code: 'HU'),
    // CountryCode(name: 'Iceland', code: 'IS'),
    // CountryCode(name: 'India', code: 'IN'),
    // CountryCode(name: 'Indonesia', code: 'ID'),
    // CountryCode(name: 'Iran', code: 'IR'),
    // CountryCode(name: 'Iraq', code: 'IQ'),
    // CountryCode(name: 'Ireland', code: 'IE'),
    // CountryCode(name: 'Isle of Man', code: 'IM'),
    // CountryCode(name: 'Israel', code: 'IL'),
    // CountryCode(name: 'Italy', code: 'IT'),
    // CountryCode(name: 'Jamaica', code: 'JM'),
    // CountryCode(name: 'Japan', code: 'JP'),
    // CountryCode(name: 'Jersey', code: 'JE'),
    // CountryCode(name: 'Jordan', code: 'JO'),
    // CountryCode(name: 'Kazakhstan', code: 'KZ'),
    // CountryCode(name: 'Kenya', code: 'KE'),
    // CountryCode(name: 'Kiribati', code: 'KI'),
    // CountryCode(name: 'Korea, Republic of', code: 'KR'),
    // CountryCode(name: 'Kuwait', code: 'KW'),
    // CountryCode(name: 'Kyrgyzstan', code: 'KG'),
    // CountryCode(name: 'Latvia', code: 'LV'),
    // CountryCode(name: 'Lebanon', code: 'LB'),
    // CountryCode(name: 'Lesotho', code: 'LS'),
    // CountryCode(name: 'Liberia', code: 'LR'),
    // CountryCode(name: 'Liechtenstein', code: 'LI'),
    // CountryCode(name: 'Lithuania', code: 'LT'),
    // CountryCode(name: 'Luxembourg', code: 'LU'),
    // CountryCode(name: 'Macao', code: 'MO'),
    // CountryCode(name: 'Madagascar', code: 'MG'),
    // CountryCode(name: 'Malawi', code: 'MW'),
    // CountryCode(name: 'Malaysia', code: 'MY'),
    // CountryCode(name: 'Maldives', code: 'MV'),
    // CountryCode(name: 'Mali', code: 'ML'),
    // CountryCode(name: 'Malta', code: 'MT'),
    // CountryCode(name: 'Marshall Islands', code: 'MH'),
    // CountryCode(name: 'Martinique', code: 'MQ'),
    // CountryCode(name: 'Mauritania', code: 'MR'),
    // CountryCode(name: 'Mauritius', code: 'MU'),
    // CountryCode(name: 'Mayotte', code: 'YT'),
    // CountryCode(name: 'Moldova, Republic of', code: 'MD'),
    // CountryCode(name: 'Monaco', code: 'MC'),
    // CountryCode(name: 'Mongolia', code: 'MN'),
    // CountryCode(name: 'Montserrat', code: 'MS'),
    // CountryCode(name: 'Morocco', code: 'MA'),
    // CountryCode(name: 'Mozambique', code: 'MZ'),
    // CountryCode(name: 'Myanmar', code: 'MM'),
    // CountryCode(name: 'Namibia', code: 'NA'),
    // CountryCode(name: 'Nauru', code: 'NR'),
    // CountryCode(name: 'Nepal', code: 'NP'),
    // CountryCode(name: 'Netherlands', code: 'NL'),
    // CountryCode(name: 'Netherlands Antilles', code: 'AN'),
    // CountryCode(name: 'New Caledonia', code: 'NC'),
    // CountryCode(name: 'New Zealand', code: 'NZ'),
    // CountryCode(name: 'Nicaragua', code: 'NI'),
    // CountryCode(name: 'Niger', code: 'NE'),
    // CountryCode(name: 'Nigeria', code: 'NG'),
    // CountryCode(name: 'Niue', code: 'NU'),
    // CountryCode(name: 'Norfolk Island', code: 'NF'),
    // CountryCode(name: 'Northern Mariana Islands', code: 'MP'),
    // CountryCode(name: 'Norway', code: 'NO'),
    // CountryCode(name: 'Oman', code: 'OM'),
    // CountryCode(name: 'Pakistan', code: 'PK'),
    // CountryCode(name: 'Palau', code: 'PW'),
    // CountryCode(name: 'Palestinian Territory, Occupied', code: 'PS'),
    // CountryCode(name: 'Panama', code: 'PA'),
    // CountryCode(name: 'Papua New Guinea', code: 'PG'),
    // CountryCode(name: 'Paraguay', code: 'PY'),
    // CountryCode(name: 'Peru', code: 'PE'),
    // CountryCode(name: 'Philippines', code: 'PH'),
    // CountryCode(name: 'Pitcairn', code: 'PN'),
    // CountryCode(name: 'Poland', code: 'PL'),
    // CountryCode(name: 'Portugal', code: 'PT'),
    // CountryCode(name: 'Puerto Rico', code: 'PR'),
    // CountryCode(name: 'Qatar', code: 'QA'),
    // CountryCode(name: 'Reunion', code: 'RE'),
    // CountryCode(name: 'Romania', code: 'RO'),
    // CountryCode(name: 'Russian Federation', code: 'RU'),
    // CountryCode(name: 'RWANDA', code: 'RW'),
    // CountryCode(name: 'Saint Helena', code: 'SH'),
    // CountryCode(name: 'Saint Kitts and Nevis', code: 'KN'),
    // CountryCode(name: 'Saint Lucia', code: 'LC'),
    // CountryCode(name: 'Saint Pierre and Miquelon', code: 'PM'),
    // CountryCode(name: 'Saint Vincent and the Grenadines', code: 'VC'),
    // CountryCode(name: 'Samoa', code: 'WS'),
    // CountryCode(name: 'San Marino', code: 'SM'),
    // CountryCode(name: 'Sao Tome and Principe', code: 'ST'),
    // CountryCode(name: 'Saudi Arabia', code: 'SA'),
    // CountryCode(name: 'Senegal', code: 'SN'),
    // CountryCode(name: 'Serbia and Montenegro', code: 'CS'),
    // CountryCode(name: 'Seychelles', code: 'SC'),
    // CountryCode(name: 'Sierra Leone', code: 'SL'),
    // CountryCode(name: 'Singapore', code: 'SG'),
    // CountryCode(name: 'Slovakia', code: 'SK'),
    // CountryCode(name: 'Slovenia', code: 'SI'),
    // CountryCode(name: 'Solomon Islands', code: 'SB'),
    // CountryCode(name: 'Somalia', code: 'SO'),
    // CountryCode(name: 'South Africa', code: 'ZA'),
    // CountryCode(name: 'Spain', code: 'ES'),
    // CountryCode(name: 'Sri Lanka', code: 'LK'),
    // CountryCode(name: 'Sudan', code: 'SD'),
    // CountryCode(name: 'Suriname', code: 'SR'),
    // CountryCode(name: 'Svalbard and Jan Mayen', code: 'SJ'),
    // CountryCode(name: 'Swaziland', code: 'SZ'),
    // CountryCode(name: 'Sweden', code: 'SE'),
    // CountryCode(name: 'Switzerland', code: 'CH'),
    // CountryCode(name: 'Syrian Arab Republic', code: 'SY'),
    // CountryCode(name: 'Taiwan, Province of China', code: 'TW'),
    // CountryCode(name: 'Tajikistan', code: 'TJ'),
    // CountryCode(name: 'Tanzania, United Republic of', code: 'TZ'),
    // CountryCode(name: 'Thailand', code: 'TH'),
    // CountryCode(name: 'Timor-Leste', code: 'TL'),
    // CountryCode(name: 'Togo', code: 'TG'),
    // CountryCode(name: 'Tokelau', code: 'TK'),
    // CountryCode(name: 'Tonga', code: 'TO'),
    // CountryCode(name: 'Trinidad and Tobago', code: 'TT'),
    // CountryCode(name: 'Tunisia', code: 'TN'),
    // CountryCode(name: 'Turkey', code: 'TR'),
    // CountryCode(name: 'Turkmenistan', code: 'TM'),
    // CountryCode(name: 'Turks and Caicos Islands', code: 'TC'),
    // CountryCode(name: 'Tuvalu', code: 'TV'),
    // CountryCode(name: 'Uganda', code: 'UG'),
    // CountryCode(name: 'Ukraine', code: 'UA'),
    // CountryCode(name: 'United Arab Emirates', code: 'AE'),
    // CountryCode(name: 'United Kingdom', code: 'GB'),
    // CountryCode(name: 'Uruguay', code: 'UY'),
    // CountryCode(name: 'Uzbekistan', code: 'UZ'),
    // CountryCode(name: 'Vanuatu', code: 'VU'),
    // CountryCode(name: 'Venezuela', code: 'VE'),
    // CountryCode(name: 'Viet Nam', code: 'VN'),
    // CountryCode(name: 'Virgin Islands, British', code: 'VG'),
    // CountryCode(name: 'Virgin Islands, U.S.', code: 'VI'),
    // CountryCode(name: 'Wallis and Futuna', code: 'WF'),
    // CountryCode(name: 'Western Sahara', code: 'EH'),
    // CountryCode(name: 'Yemen', code: 'YE'),
    // CountryCode(name: 'Zambia', code: 'ZM'),
    // CountryCode(name: 'Zimbabwe', code: 'ZW'),
  ];
}
